--CREATE DATABASE SupremeLiftDb

GO
CREATE TABLE [User]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(MAX) NOT NULL,
	[Age] INT NOT NULL,
	[Weight] FLOAT NOT NULL,
	[Height] FLOAT NOT NULL,
	[Sex] INT NOT NULL
)

GO
CREATE TABLE [Excercise]
(
	[ExcerciseId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(MAX) NOT NULL,
	[CaloriesBurned] FLOAT NOT NULL
)