//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DAL.Models;

namespace DAL
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(RecordMetadata))]
    public partial class Record
    {
        public int RecordId { get; set; }
        public double WeightLifted { get; set; }
        public Nullable<int> Fk_ExerciseId { get; set; }
        public Nullable<int> Fk_UserId { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual User User { get; set; }
    }
}
