//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using DAL.Models;

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(WorkoutMetadata))]
    public partial class Workout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout()
        {
            this.WorkoutExercises = new HashSet<WorkoutExercise>();
        }
    
        public int WorkoutId { get; set; }
        public Nullable<int> Fk_UserId { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutExercise> WorkoutExercises { get; set; }
    }
}
