//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutExercise
    {
        public int WorkoutExerciseId { get; set; }
        public int Sets { get; set; }
        public int Reps { get; set; }
        public Nullable<int> Fk_ExerciseId { get; set; }
        public Nullable<int> Fk_WorkoutId { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
